name: QuickShulker
version: '${project.version}'
main: org.tahoma.quickshulkers.QuickShulker
api-version: '1.16'
author: Tahoma34
softdepend: [CombatLogX]

commands:
  quickshulker:
    description: Main commands QuickShulker
    aliases: [qs,qshulker]
    usage: /<command> <reload|autoup|autoopen>
    permission: quickshulker.use
    permission-message: You dont have permission.
